package_assets: on

javascripts:
  common:
    - scripts/jquery.min.js
    - scripts/cake.js
    - scripts/playtomic.v2.2.min.js
  game:
    - scripts/game/Block.js
    - scripts/game/Shape.js
    - scripts/game/ScorePanel.js
    - scripts/game/GameContainer.js
    - scripts/game/world.js
